# Generated by Django 5.2.9 on 2026-01-07 16:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, db_column='LogoUrl', max_length=500, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, db_column='TaxCode', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=18, null=True)),
                ('duration_days', models.IntegerField(blank=True, db_column='DurationDays', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], db_column='Role', max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('fullname', models.CharField(blank=True, db_column='Fullname', max_length=255, null=True)),
                ('avatar_url', models.ImageField(db_column='AvatarUrl', null=True, upload_to='ava/%Y/%m')),
                ('auth_provider', models.CharField(blank=True, db_column='AuthProvider', max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(db_column='CompanyId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to='database.companies')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auditlogs',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, db_column='EntityType', max_length=255)),
                ('entity_id', models.CharField(blank=True, db_column='EntityId', max_length=255)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('detail', models.JSONField(blank=True, db_column='Detail')),
                ('ip_address', models.CharField(blank=True, db_column='IPAddress', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('Actor', models.ForeignKey(blank=True, db_column='ActorId', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'systemlogs',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('is_open_to_work', models.BooleanField(db_column='OpenToWork', default=False)),
                ('current_job_title', models.CharField(blank=True, db_column='CurrentJobTitle', max_length=100, null=True)),
                ('expected_salary', models.BigIntegerField(blank=True, db_column='ExpectedSalary', null=True)),
                ('experience', models.JSONField(blank=True, db_column='Experience', null=True)),
                ('user', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Cvs',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, db_column='FileName', max_length=255, null=True)),
                ('file_url', models.FileField(db_column='FileUrl', null=True, upload_to='cvs/%Y/%m/')),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('candidate', models.ForeignKey(blank=True, db_column='CandidateId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='database.candidates')),
            ],
            options={
                'db_table': 'cvs',
            },
        ),
        migrations.CreateModel(
            name='Cvanalysisresult',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('target_job', models.CharField(blank=True, db_column='TargetJob', max_length=255, null=True)),
                ('overall_score', models.FloatField(db_column='OverallScore', db_index=True, default=0.0)),
                ('content_score', models.FloatField(db_column='ContentScore', default=0.0)),
                ('format_score', models.FloatField(db_column='FormatScore', default=0.0)),
                ('ai_response_json', models.JSONField(blank=True, db_column='AIResponseJson', null=True)),
                ('format_analysis_json', models.JSONField(blank=True, db_column='FormatAnalysisJson', null=True)),
                ('extracted_email', models.CharField(blank=True, db_column='ExtractedEmail', max_length=255, null=True)),
                ('extracted_phone', models.CharField(blank=True, db_column='ExtractedPhone', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('cv', models.ForeignKey(blank=True, db_column='CVId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='database.cvs')),
            ],
            options={
                'db_table': 'cvanalysisresult',
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('location', models.CharField(blank=True, db_column='location', max_length=255)),
                ('skill', models.JSONField(db_column='Skills', null=True)),
                ('salary_min', models.BigIntegerField(blank=True, db_column='SalaryMin', null=True)),
                ('salary_max', models.BigIntegerField(blank=True, db_column='SalaryMax', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='CategoryId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='database.categories')),
                ('companiesid', models.ForeignKey(blank=True, db_column='CompanyId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='database.companies')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('candidateid', models.ForeignKey(blank=True, db_column='CandidateId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='database.candidates')),
                ('cvsid', models.ForeignKey(blank=True, db_column='CvId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='database.cvs')),
                ('jobid', models.ForeignKey(blank=True, db_column='JobId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='database.jobs')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='job',
            field=models.ForeignKey(db_column='JobId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User', to='database.jobs'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('message', models.TextField(db_column='Message')),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('receiver', models.ForeignKey(db_column='Receiver', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('package', models.ForeignKey(blank=True, db_column='PackageId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='database.packages')),
                ('user', models.ForeignKey(blank=True, db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
