# Generated by Django 6.0 on 2025-12-26 14:46

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, db_column='LogoUrl', max_length=500, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('tax_code', models.CharField(blank=True, db_column='TaxCode', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=255, null=True)),
                ('username', models.CharField(db_column='Username', max_length=255, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=255, unique=True)),
                ('fullname', models.CharField(blank=True, db_column='Fullname', max_length=255, null=True)),
                ('avatar_url', models.CharField(blank=True, db_column='AvatarUrl', max_length=500, null=True)),
                ('auth_provider', models.CharField(blank=True, db_column='AuthProvider', max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=255, null=True, unique=True)),
                ('user', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='rdmin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Admins',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=500, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, db_column='DateOfBirth', null=True)),
                ('is_open_to_work', models.BooleanField(db_column='OpenToWork', default=False)),
                ('current_job_title', models.CharField(blank=True, db_column='CurrentJobTitle', max_length=100, null=True)),
                ('expected_salary', models.BigIntegerField(blank=True, db_column='ExpectedSalary', null=True)),
                ('experience', models.JSONField(blank=True, db_column='Experience', null=True)),
                ('user', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(blank=True, db_column='CompaniesId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters', to='database.companies')),
                ('user', models.OneToOneField(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Recruiters',
            },
        ),
    ]
