# Generated by Django 5.2.9 on 2026-01-19 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='isdeleted',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='note',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='cvs',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='isdeleted',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='note',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='applications',
            name='job_status',
            field=models.CharField(blank=True, db_column='JobStatus', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='system_status',
            field=models.CharField(blank=True, db_column='SystemStatus', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='created_by',
            field=models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='isdeleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
        migrations.AddField(
            model_name='candidates',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='updated_by',
            field=models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True),
        ),
        migrations.AddField(
            model_name='cvanalysisresult',
            name='created_by',
            field=models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvanalysisresult',
            name='updated_by',
            field=models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(blank=True, db_column='Status', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='CareerRoadMap',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('target_job', models.CharField(blank=True, db_column='TargetJob', max_length=255, null=True)),
                ('roadmap_json', models.JSONField(blank=True, db_column='RoadmapJson', null=True)),
                ('candidate', models.ForeignKey(blank=True, db_column='CandidateId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='career_roadmaps', to='database.candidates')),
                ('cv', models.ForeignKey(blank=True, db_column='CVId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_roadmaps', to='database.cvs')),
            ],
            options={
                'db_table': 'careerroadmap',
            },
        ),
    ]
