# Generated by Django 5.2.9 on 2026-01-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar_url',
            field=models.ImageField(db_column='AvatarUrl', null=True, upload_to='ava/%Y/%m'),
        ),
    ]
