# Generated by Django 5.2.9 on 2026-01-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='company',
            field=models.CharField(blank=True, db_column='Company', max_length=255, null=True),
        ),
    ]
