# Generated by Django 6.0 on 2025-12-27 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('rolename', models.CharField(db_column='RoleName', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.ForeignKey(blank=True, db_column='RoleId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='database.roles'),
        ),
    ]
