# Generated by Django 6.0 on 2025-12-27 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_roles_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airequest',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('input_hash', models.TextField(blank=True, db_column='InputHash', null=True)),
                ('output', models.JSONField(blank=True, db_column='Output', null=True)),
                ('typename', models.CharField(blank=True, db_column='TypeName', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'airequest',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=18, null=True)),
                ('duration_days', models.IntegerField(blank=True, db_column='DurationDays', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Auditlogs',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(blank=True, db_column='EntityType', max_length=255)),
                ('entity_id', models.CharField(blank=True, db_column='EntityId', max_length=255)),
                ('action', models.CharField(blank=True, db_column='Action', max_length=255, null=True)),
                ('detail', models.JSONField(blank=True, db_column='Detail')),
                ('ip_address', models.CharField(blank=True, db_column='IPAddress', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('Actor', models.ForeignKey(blank=True, db_column='ActorId', on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'systemlogs',
            },
        ),
        migrations.CreateModel(
            name='Cvs',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, db_column='FileName', max_length=255, null=True)),
                ('file_url', models.CharField(blank=True, db_column='FileUrl', max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('candidate', models.ForeignKey(blank=True, db_column='CandidateId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CV', to='database.candidates')),
            ],
            options={
                'db_table': 'cvs',
            },
        ),
        migrations.CreateModel(
            name='Cvanalysisresult',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
                ('experience', models.JSONField(blank=True, db_column='Experience', null=True)),
                ('skill', models.JSONField(blank=True, db_column='Skill', null=True)),
                ('matchingkeyword', models.JSONField(blank=True, db_column='MatchingKeyWord', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('ai_request', models.ForeignKey(blank=True, db_column='AIRequestId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_result', to='database.airequest')),
                ('cv', models.ForeignKey(blank=True, db_column='CVId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cv_result', to='database.cvs')),
            ],
            options={
                'db_table': 'cvanalysisresult',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('requirement', models.JSONField(blank=True, db_column='Requirement', null=True)),
                ('salarymin', models.IntegerField(blank=True, db_column='SalaryMin', null=True)),
                ('salarymax', models.IntegerField(blank=True, db_column='SalaryMax', null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=255, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='CategoryId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='database.categories')),
                ('companiesid', models.ForeignKey(blank=True, db_column='CompanyId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='database.companies')),
                ('recruiter', models.ForeignKey(blank=True, db_column='RecruiterId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='database.recruiters')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Jobmatching',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('matchscore', models.FloatField(blank=True, db_column='MatchScore', null=True)),
                ('airequestid', models.ForeignKey(blank=True, db_column='AIRequestId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Jobmatching', to='database.airequest')),
                ('candidateid', models.ForeignKey(blank=True, db_column='CandidateId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jobmatching', to='database.candidates')),
                ('jobid', models.ForeignKey(blank=True, db_column='JobId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Jobmatching', to='database.jobs')),
            ],
            options={
                'db_table': 'jobmatching',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('coverletter', models.CharField(blank=True, db_column='CoverLetter', max_length=1000, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('candidateid', models.ForeignKey(blank=True, db_column='CandidateId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='database.candidates')),
                ('cvsid', models.ForeignKey(blank=True, db_column='CvId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='database.cvs')),
                ('jobid', models.ForeignKey(blank=True, db_column='JobId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='database.jobs')),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('conversation', models.ForeignKey(blank=True, db_column='ConversationId', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='database.conversation')),
                ('receiver', models.ForeignKey(blank=True, db_column='ReceiverId', on_delete=django.db.models.deletion.CASCADE, related_name='message_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, db_column='SenderId', on_delete=django.db.models.deletion.CASCADE, related_name='message_sended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='NotificationReceivers',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(db_column='IsRead', default=False)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('read_date', models.DateTimeField(blank=True, db_column='ReadDate', null=True)),
                ('user', models.ForeignKey(db_column='ReceiverId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificationsreceivers',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=255, null=True)),
                ('message', models.TextField(db_column='Message')),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('receiver', models.ManyToManyField(related_name='notifications_received', through='database.NotificationReceivers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, db_column='SenderId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sended', to='database.admins')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.AddField(
            model_name='notificationreceivers',
            name='notification',
            field=models.ForeignKey(db_column='NotificationId', on_delete=django.db.models.deletion.CASCADE, to='database.notifications'),
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.CharField(db_column='Id', max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('end_date', models.DateTimeField(blank=True, db_column='EndDate', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('package', models.ForeignKey(blank=True, db_column='PackageId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='database.packages')),
                ('user', models.ForeignKey(blank=True, db_column='UserId', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
