# Generated by Django 5.2.9 on 2026-01-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], db_column='Role', max_length=255, null=True),
        ),
    ]
