# Generated by Django 5.2.9 on 2026-01-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_applications_status_remove_cvs_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiters',
            name='created_by',
            field=models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='isdeleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='updated_by',
            field=models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruiters',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True),
        ),
    ]
