# Generated by Django 5.2.9 on 2026-01-19 08:43

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_recruiters_created_by_recruiters_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('id', models.CharField(db_column='Id', default=django.db.models.fields.UUIDField, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('target_job', models.CharField(db_column='TargetJob', max_length=100)),
                ('level', models.CharField(db_column='Level', max_length=50)),
                ('max_turns', models.IntegerField(db_column='Maxturn', default=5)),
                ('is_finished', models.BooleanField(db_column='IsFinished', default=False)),
                ('final_score', models.IntegerField(blank=True, db_column='FinalScore', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('id', models.CharField(db_column='Id', default=django.db.models.fields.UUIDField, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], db_column='Role', max_length=10)),
                ('content', models.TextField(db_column='Content')),
                ('turn_index', models.IntegerField(db_column='TurnIndex')),
                ('conversation', models.ForeignKey(db_column='ConversationId', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='database.conversation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
