# Generated by Django 5.2.9 on 2026-01-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_conversation_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='auditlogs',
            table='auditlogs',
        ),
    ]
