# Generated by Django 5.2.9 on 2026-01-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_auditlogs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conversation',
            table='conversation',
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
