# Generated by Django 5.2.9 on 2026-01-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_conversation_table_alter_message_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvs',
            name='created_by',
            field=models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True),
        ),
        migrations.AddField(
            model_name='cvs',
            name='isdeleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
        migrations.AddField(
            model_name='cvs',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvs',
            name='updated_by',
            field=models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cvs',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True),
        ),
    ]
