# Generated by Django 5.2.9 on 2026-01-19 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_cvs_created_by_cvs_created_date_cvs_isdeleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(db_column='UserId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobs',
            name='created_by',
            field=models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='isdeleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
        migrations.AddField(
            model_name='jobs',
            name='note',
            field=models.CharField(blank=True, db_column='Note', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='updated_by',
            field=models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobs',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.JSONField(db_column='Content'),
        ),
    ]
