# Generated by Django 5.2.9 on 2026-01-31 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_conversation_user_jobs_created_by_jobs_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(blank=True, db_column='ScheduledTime', null=True)),
                ('at', models.CharField(blank=True, db_column='At', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('feedback', models.TextField(blank=True, db_column='Feedback', null=True)),
                ('candidate', models.ForeignKey(blank=True, db_column='CandidateId', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='database.candidates')),
                ('job', models.ForeignKey(blank=True, db_column='JobId', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='database.jobs')),
                ('recruiter', models.ForeignKey(blank=True, db_column='RecruiterId', on_delete=django.db.models.deletion.CASCADE, related_name='interviews_scheduled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
    ]
