# Generated by Django 5.2.9 on 2026-01-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_conversation_user_jobs_created_by_jobs_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvs',
            name='file_hash',
            field=models.CharField(blank=True, db_column='FileHash', db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cvs',
            name='file_size',
            field=models.IntegerField(blank=True, db_column='FileSize', null=True),
        ),
    ]
