# Generated by Django 5.2.9 on 2026-01-31 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_cvs_file_hash_cvs_file_size'),
        ('database', '0009_interviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='application',
            field=models.ForeignKey(blank=True, db_column='ApplicationId', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='database.applications'),
        ),
    ]
