# Generated by Django 5.2.9 on 2026-01-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_cvs_file_hash_cvs_file_size'),
        ('database', '0009_interviews'),
    ]

    operations = [
    ]
