# Generated by Django 5.2.9 on 2026-02-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_merge_20260201_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvanalysisresult',
            name='extracted_skill',
            field=models.JSONField(blank=True, db_column='ExtractedSkill', null=True),
        ),
    ]
