# Generated by Django 5.2.9 on 2026-02-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_cvanalysisresult_extracted_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='location',
            field=models.CharField(blank=True, db_column='Location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interviews',
            name='notes',
            field=models.TextField(blank=True, db_column='Notes', null=True),
        ),
    ]
