# Generated by Django 5.2.9 on 2026-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_interviews_location_interviews_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvanalysisresult',
            name='extracted_skill',
            field=models.JSONField(blank=True, db_column='ExtractedSkill', default=list, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='skill',
            field=models.JSONField(db_column='Skills', default=list, null=True),
        ),
    ]
