# Generated by Django 5.2.9 on 2026-02-06 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_remove_applications_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvTemplate',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('image_url', models.CharField(blank=True, db_column='ImageUrl', max_length=500, null=True)),
                ('file_url', models.FileField(blank=True, db_column='FileUrl', null=True, upload_to='templates/cv/')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
            options={
                'db_table': 'cv_templates',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('question', models.TextField(db_column='Question')),
                ('category', models.CharField(db_column='Category', max_length=100)),
                ('difficulty', models.CharField(db_column='Difficulty', max_length=50)),
            ],
            options={
                'db_table': 'interview_questions',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, db_column='CreatedDate', null=True)),
                ('created_by', models.CharField(blank=True, db_column='CreatedBy', max_length=255, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, db_column='UpdatedDate', null=True)),
                ('updated_by', models.CharField(blank=True, db_column='UpdatedBy', max_length=255, null=True)),
                ('isdeleted', models.BooleanField(db_column='IsDeleted', default=False)),
                ('note', models.CharField(blank=True, db_column='Note', max_length=255, null=True)),
                ('id', models.CharField(db_column='Id', default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('type', models.CharField(db_column='Type', max_length=50)),
                ('file', models.FileField(db_column='File', upload_to='resources/')),
                ('size', models.CharField(blank=True, db_column='Size', max_length=50, null=True)),
            ],
            options={
                'db_table': 'resources',
                'ordering': ['-created_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='cvs',
            options={'ordering': ['-created_date']},
        ),
    ]
