# Generated by Django 5.2.9 on 2026-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_remove_applications_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvs',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='companies',
            name='logo_url',
            field=models.ImageField(db_column='LogoUrl', null=True, upload_to='logo/%Y/%m'),
        ),
    ]
