# Generated by Django 5.2.9 on 2026-02-07 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_cvs_options_alter_companies_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='recruiter',
            field=models.ForeignKey(blank=True, db_column='RecruiterId', on_delete=django.db.models.deletion.CASCADE, related_name='interviews_scheduled', to='database.recruiters'),
        ),
    ]
